// Bloques try catch
const n1 = 20;
const n3 = 30;

console.log(n1);

try { //Intenta hacer esto:
    console.log(n2);    
} catch (error) { // si no puedes, d√≠me que error aparece:
    console.log(error);
}

console.log(n3);